// ─── Standardized Authentication Error Codes ────────────────────────────────
// Controllers return these codes exclusively. Never use raw strings.

const AUTH_ERRORS = {
  // Credential errors
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Account state
  USER_EXISTS: 'USER_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',

  // Registration
  REGISTRATION_ERROR: 'REGISTRATION_ERROR',

  // Session / Token errors
  REFRESH_TOKEN_REQUIRED: 'REFRESH_TOKEN_REQUIRED',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  REFRESH_INVALID: 'REFRESH_INVALID',
  REFRESH_FAILED: 'REFRESH_FAILED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',

  // Device / 2FA
  INVALID_2FA_CODE: 'INVALID_2FA_CODE',
  BROWSER_LOCKED: 'BROWSER_LOCKED',
  SESSION_LIMIT: 'SESSION_LIMIT',
  INVALID_VERIFICATION_CODE: 'INVALID_VERIFICATION_CODE',

  // Logout
  LOGOUT_ERROR: 'LOGOUT_ERROR',
  LOGOUT_ALL_ERROR: 'LOGOUT_ALL_ERROR',

  // Sessions
  SESSIONS_ERROR: 'SESSIONS_ERROR',
  REVOKE_ERROR: 'REVOKE_ERROR',

  // Password reset
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_LOCKED: 'OTP_LOCKED',
  INVALID_OTP: 'INVALID_OTP',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  RESET_SESSION_EXPIRED: 'RESET_SESSION_EXPIRED',
  RESEND_COOLDOWN: 'RESEND_COOLDOWN',

  // Password change
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  PASSWORD_CHANGE_ERROR: 'PASSWORD_CHANGE_ERROR',

  // Profile
  PROFILE_UPDATE_ERROR: 'PROFILE_UPDATE_ERROR',

  // Admin
  ADMIN_LOGIN_FAILED: 'ADMIN_LOGIN_FAILED',
  ADMIN_NOT_FOUND: 'ADMIN_NOT_FOUND',

  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',

  // ── Enterprise PRD Standardized Codes ──────────────────────────────────
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_REFRESH_INVALID: 'AUTH_REFRESH_INVALID',
  AUTH_REFRESH_REUSED: 'AUTH_REFRESH_REUSED',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_INVALID_COOKIE: 'AUTH_INVALID_COOKIE',
  AUTH_INVALID_CSRF: 'AUTH_INVALID_CSRF',
  AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_INVALID_VERIFICATION_TOKEN: 'AUTH_INVALID_VERIFICATION_TOKEN',
  AUTH_VERIFICATION_TOKEN_EXPIRED: 'AUTH_VERIFICATION_TOKEN_EXPIRED',
  AUTH_EMAIL_ALREADY_VERIFIED: 'AUTH_EMAIL_ALREADY_VERIFIED',
  AUTH_MFA_REQUIRED: 'AUTH_MFA_REQUIRED',
  AUTH_MFA_INVALID: 'AUTH_MFA_INVALID',
  AUTH_MFA_NOT_ENABLED: 'AUTH_MFA_NOT_ENABLED',
  AUTH_BACKUP_CODE_INVALID: 'AUTH_BACKUP_CODE_INVALID',
  AUTH_RECOVERY_PENDING: 'AUTH_RECOVERY_PENDING',
  AUTH_RECOVERY_NOT_FOUND: 'AUTH_RECOVERY_NOT_FOUND',
  AUTH_RECOVERY_EXPIRED: 'AUTH_RECOVERY_EXPIRED',
  AUTH_RISK_BLOCKED: 'AUTH_RISK_BLOCKED',
  AUTH_STEP_UP_REQUIRED: 'AUTH_STEP_UP_REQUIRED',
  AUTH_IP_BLOCKED: 'AUTH_IP_BLOCKED',
};

export default AUTH_ERRORS;
