-- AlterTable
ALTER TABLE "User"
ADD COLUMN "failedLoginAttempts" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User"
ADD COLUMN "lastFailedLogin" TIMESTAMP(3);
ALTER TABLE "User"
ADD COLUMN "lastSuccessfulLogin" TIMESTAMP(3);
ALTER TABLE "User"
ADD COLUMN "lockedUntil" TIMESTAMP(3);