export const PaymentEvents = {
  ORDER_CREATED: 'payment:order:created',
  ORDER_CREATION_FAILED: 'payment:order:creation_failed',
  VERIFIED: 'payment:verified',
  VERIFICATION_FAILED: 'payment:verification_failed',
  CAPTURED: 'payment:captured',
  FAILED: 'payment:failed',
  SUCCESS: 'payment:success',
  REFUNDED: 'payment:refunded',
  PARTIALLY_REFUNDED: 'payment:partially_refunded',
  EXPIRED: 'payment:expired',
  CANCELLED: 'payment:cancelled',
  RECOVERY_INITIATED: 'payment:recovery:initiated',
  RECOVERY_COMPLETED: 'payment:recovery:completed',
  RECOVERY_FAILED: 'payment:recovery:failed',
  RECONCILIATION_STARTED: 'payment:reconciliation:started',
  RECONCILIATION_COMPLETED: 'payment:reconciliation:completed',
  SETTLEMENT_COMPLETED: 'payment:settlement:completed',
  WEBHOOK_RECEIVED: 'payment:webhook:received',
  WEBHOOK_PROCESSED: 'payment:webhook:processed',
  WEBHOOK_FAILED: 'payment:webhook:failed',
};
